---
apiVersion: v1
kind: Template
metadata:
  name: builder-image-build
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${SERVICE}
      name: ${BUILDER_IMAGE_NAME}
    spec:
      output:
        pushSecret:
          name: artifactory
        to:
          kind: DockerImage
          name: ${DOCKER_REPO_URL}/${NAMESPACE}/${BUILDER_IMAGE_NAME}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          uri: https://github.com/philipfoster/malware-orchestrator-openshift.git
          ref: master
      strategy:
        dockerStrategy:
          dockerfilePath: ./docker_builder/Dockerfile
        type: Docker
      triggers: []
parameters:
  - name: NAMESPACE
    displayName: Namespace (Openshift project)
    description: Openshift project this application resides in
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: BUILDER_IMAGE_NAME
    displayName: Name of the modified KIE server builder image
    required: true
