---
apiVersion: v1
kind: Template
metadata:
  name: build-config-template
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      output:
        pushSecret:
          name: artifactory
        to:
          kind: DockerImage
          name: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${APP_NAME}:latest
      resources: {}
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${PAM_SCM_URL}"
          ref: "${PAM_SCM_REF}"
        contextDir: /
      strategy:
        type: Source
        sourceStrategy:
          env:
          - name: KIE_SERVER_CONTAINER_DEPLOYMENT
            value: "${KIE_CONTAINER}"
          forcePull: true
          # from:
          #   kind: ImageStreamTag
          #   namespace: ${NAMESPACE}
          #   name: ${BUILDER_IMAGE_NAME}:latest
          from: 
            kind: DockerImage
            name: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${BUILDER_IMAGE_NAME}:latest
parameters:
  - name: NAMESPACE
    displayName: Namespace (Openshift project)
    description: Openshift project this application resides in
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name
  - name: PAM_SCM_URL
    required: true
    description: Link to the Git repository that the pam-orchestrator project is stored
  - name: PAM_SCM_REF
    required: false
    default: master
    description: The git ref in PAM_SCM_URL to build.
  - name: KIE_CONTAINER
    required: true
    description: The name of the KIE container to deploy.
  - name: BUILDER_IMAGE_NAME
    displayName: Name of the modified KIE server builder image
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker repo namespace
    required: true