---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app:  ${APP_NAME}
      name: ${APP_NAME}-kieserver
    spec:
      revisionHistoryLimits: 10
      strategy:
        rollingParams:
          maxSurge: 100%
          maxUnavailable: 0
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        deploymentConfig: ${APP_NAME}-kieserver
      template:
        metadata:
          name: ${APP_NAME}-kieserver
          labels:
            deploymentConfig: "${APP_NAME}-kieserver"
            application: "${APP_NAME}"
            service: "${APP_NAME}-kieserver"
            services.server.kie.org/kie-server-id: "${APP_NAME}-kieserver"
        spec:
          imagePullSecrets:
            - name: artifactory
          serviceAccountName: ${APP_NAME}-kieserver
          terminationGracePeriodSeconds: 90
          volumes:
            - name: kieserver-keystore-volume
              secret: 
                secretName: rhpam-tls-cert
            - name: kieserver-standalone-xml
              configMap:
                name: kie-standalone-template
                defaultMode: 440
                items:
                  - key: standalone.xml
                    path: standalone-openshift.xml
          containers:
            - name: "${APP_NAME}-kieserver"
              image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${BUILDER_IMAGE_NAME}:latest
              imagePullPolicy: Always
              lifecycle:
                postStart:
                  exec:
                    command:
                      - /bin/sh
                      - /opt/eap/bin/launch/jboss-kie-kieserver-hooks.sh
                preStart:
                  exec:
                    command:
                      - /bin/sh
                      - /opt/eap/bin/launch/jboss-kie-kieserver-hooks.sh
              resources:
                limits:
                  memory: "2Gi"
              volumeMounts:
                - name: kieserver-keystore-volume
                  mountPath: "/etc/kieserver-secret-volume"
                  readOnly: true
                - name: kieserver-standalone-xml
                  mountPath: /opt/eap/standalone/configuration/standalone-openshift.xml
                  subPath: standalone-openshift.xml
              ports:
                - name: jolokia
                  containerPort: 8778
                  protocol: TCP
                - name: http
                  containerPort: 8080
                  protocol: TCP 
                - name: https
                  containerPort: 8443
                  protocol: TCP 
                - name: ping
                  containerPort: 8888
                  protocol: TCP 
              env:
                - name: KIE_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: kie-admin-user
                      key: username
                - name: KIE_ADMIN_PWD
                  valueFrom:
                    secretKeyRef:
                      name: kie-admin-user
                      key: password
                - name: KIE_SERVER_MODE
                  value: "${KIE_SERVER_MODE}"
                - name: KIE_MBEANS
                  value: "true"
                - name: DROOLS_SERVER_FILTER_CLASS
                  value: "true"
                - name: PROMETHEUS_SERVER_EXT_DISABLED
                  value: "true"
                - name: KIE_SERVER_BYPASS_AUTH_USER
                  value: "false"
                - name: KIE_SERVER_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['services.server.kie.org/kie-server-id']
                # - name: KIE_SERVER_ROUTE_NAME
                #   value: "insecure-${APP_NAMEE}-kieserver"
                # - name: KIE_SERVER_ROUTER_SERVICE
                #   value: "${APP_NAME}-smartrouter"
                - name: KIE_SERVER_CONTAINER_DEPLOYMENT
                  value: "${KIE_CONTAINER}"
                # - name: MAVEN_MIRROR_URL
                #   value: "${MAVEN_MIRROR_URL}"
                # - name: MAVEN_MIRROR_OF
                #   value: "${MAVEN_MIRROR_OF}"
                # - name: MAVEN_REPOS
                #   value: "RHPAMCENTR,EXTERNAL"
                # - name: RHPAMCENTR_MAVEN_REPO_ID
                #   value: "repo-rhpamcentr"
                # - name: RHPAMCENTR_MAVEN_REPO_SERVICE
                #   value: "${BUSINESS_CENTRAL_SERVICE}"
                # - name: RHPAMCENTR_MAVEN_REPO_PATH
                #   value: "/maven2/"
                # - name: RHPAMCENTR_MAVEN_REPO_USERNAME
                #   valueFrom:
                #     secretKeyRef:
                #       name: "${CREDENTIALS_SECRET}"
                #       key: KIE_ADMIN_USER
                # - name: RHPAMCENTR_MAVEN_REPO_PASSWORD
                #   valueFrom:
                #     secretKeyRef:
                #       name: "${CREDENTIALS_SECRET}"
                #       key: KIE_ADMIN_PWD
                # - name: EXTERNAL_MAVEN_REPO_ID
                #   value: "${MAVEN_REPO_ID}"
                # - name: EXTERNAL_MAVEN_REPO_URL
                #   value: "${MAVEN_REPO_URL}"
                # - name: EXTERNAL_MAVEN_REPO_USERNAME
                #   value: "${MAVEN_REPO_USERNAME}"
                # - name: EXTERNAL_MAVEN_REPO_PASSWORD
                #   value: "${MAVEN_REPO_PASSWORD}"
                # - name: KIE_SERVER_PERSISTENCE_DS
                #   value: "${KIE_SERVER_PERSISTENCE_DS}"
                # - name: DATASOURCES
                #   value: "RHPAM"
                # - name: RHPAM_DATABASE
                #   value: "${KIE_SERVER_EXTERNALDB_DB}"
                # - name: RHPAM_JNDI
                #   value: "${KIE_SERVER_PERSISTENCE_DS}"
                # - name: RHPAM_JTA
                #   value: "true"
                ## External DB driver settings BEGIN
                # - name: RHPAM_DRIVER
                #   value: "${KIE_SERVER_EXTERNALDB_DRIVER}"
                # - name: RHPAM_DRIVER
                #   value: "mysql"
                # - name: KIE_SERVER_PERSISTENCE_DIALECT
                #   value: "${KIE_SERVER_EXTERNALDB_DIALECT}"
                # - name: RHPAM_USERNAME
                #   value: "${KIE_SERVER_EXTERNALDB_USER}"
                # - name: RHPAM_PASSWORD
                #   value: "${KIE_SERVER_EXTERNALDB_PWD}"
                # - name: RHPAM_SERVICE_HOST
                #   value: "${KIE_SERVER_EXTERNALDB_SERVICE_HOST}"
                # - name: RHPAM_SERVICE_PORT
                #   value: "${KIE_SERVER_EXTERNALDB_SERVICE_PORT}"
                ## External DB driver settings END
                - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                  value: "30000"
                # - name: HTTPS_KEYSTORE_DIR
                #   value: /etc/kieserver-secret-volume
                # - name: HTTPS_KEYSTORE
                #   value: keystore.jks
                # - name: HTTPS_NAME
                #   value: rhpam
                # - name: HTTPS_PASSWORD
                #   value: password
                - name: KIE_SERVER_MGMT_DISABLED
                  value: "true" 
                - name: KIE_SERVER_STARTUP_STRATEGY
                  value: "OpenShiftStartupStrategy"
                - name: JGROUPS_PING_PROTOCOL
                  value: "openshift.DNS_PING"
                - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                  value: ${APP_NAME}-kieserver-ping
                - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                  value: "8888"
                #   - name: SSO_URL
                #   value: "${SSO_URL}"
                # - name: SSO_OPENIDCONNECT_DEPLOYMENTS
                #   value: "ROOT.war"
                # - name: SSO_REALM
                #   value: "${SSO_REALM}"
                # - name: SSO_SECRET
                #   value: "${KIE_SERVER_SSO_SECRET}"
                # - name: SSO_CLIENT
                #   value: "${KIE_SERVER_SSO_CLIENT}"
                # - name: SSO_USERNAME
                #   value: "${SSO_USERNAME}"
                # - name: SSO_PASSWORD
                #   value: "${SSO_PASSWORD}"
                # - name: SSO_DISABLE_SSL_CERTIFICATE_VALIDATION
                #   value: "${SSO_DISABLE_SSL_CERTIFICATE_VALIDATION}"
                # - name: SSO_PRINCIPAL_ATTRIBUTE
                #   value: "${SSO_PRINCIPAL_ATTRIBUTE}"
                # - name: HOSTNAME_HTTP
                #   value: "${KIE_SERVER_HOSTNAME_HTTP}"
                # - name: HOSTNAME_HTTPS
                #   value: "${KIE_SERVER_HOSTNAME_HTTPS}"
                # - name: AUTH_LDAP_URL
                #   value: "${AUTH_LDAP_URL}"
                # - name: AUTH_LDAP_BIND_DN
                #   value: "${AUTH_LDAP_BIND_DN}"
                # - name: AUTH_LDAP_BIND_CREDENTIAL
                #   value: "${AUTH_LDAP_BIND_CREDENTIAL}"
                # - name: AUTH_LDAP_JAAS_SECURITY_DOMAIN
                #   value: "${AUTH_LDAP_JAAS_SECURITY_DOMAIN}"
                # - name: AUTH_LDAP_BASE_CTX_DN
                #   value: "${AUTH_LDAP_BASE_CTX_DN}"
                # - name: AUTH_LDAP_BASE_FILTER
                #   value: "${AUTH_LDAP_BASE_FILTER}"
                # - name: AUTH_LDAP_SEARCH_SCOPE
                #   value: "${AUTH_LDAP_SEARCH_SCOPE}"
                # - name: AUTH_LDAP_SEARCH_TIME_LIMIT
                #   value: "${AUTH_LDAP_SEARCH_TIME_LIMIT}"
                # - name: AUTH_LDAP_DISTINGUISHED_NAME_ATTRIBUTE
                #   value: "${AUTH_LDAP_DISTINGUISHED_NAME_ATTRIBUTE}"
                # - name: AUTH_LDAP_PARSE_USERNAME
                #   value: "${AUTH_LDAP_PARSE_USERNAME}"
                # - name: AUTH_LDAP_USERNAME_BEGIN_STRING
                #   value: "${AUTH_LDAP_USERNAME_BEGIN_STRING}"
                # - name: AUTH_LDAP_USERNAME_END_STRING
                #   value: "${AUTH_LDAP_USERNAME_END_STRING}"
                # - name: AUTH_LDAP_ROLE_ATTRIBUTE_ID
                #   value: "${AUTH_LDAP_ROLE_ATTRIBUTE_ID}"
                # - name: AUTH_LDAP_ROLES_CTX_DN
                #   value: "${AUTH_LDAP_ROLES_CTX_DN}"
                # - name: AUTH_LDAP_ROLE_FILTER
                #   value: "${AUTH_LDAP_ROLE_FILTER}"
                # - name: AUTH_LDAP_ROLE_RECURSION
                #   value: "${AUTH_LDAP_ROLE_RECURSION}"
                # - name: AUTH_LDAP_DEFAULT_ROLE
                #   value: "${AUTH_LDAP_DEFAULT_ROLE}"
                # - name: AUTH_LDAP_ROLE_NAME_ATTRIBUTE_ID
                #   value: "${AUTH_LDAP_ROLE_NAME_ATTRIBUTE_ID}"
                # - name: AUTH_LDAP_PARSE_ROLE_NAME_FROM_DN
                #   value: "${AUTH_LDAP_PARSE_ROLE_NAME_FROM_DN}"
                # - name: AUTH_LDAP_ROLE_ATTRIBUTE_IS_DN
                #   value: "${AUTH_LDAP_ROLE_ATTRIBUTE_IS_DN}"
                # - name: AUTH_LDAP_REFERRAL_USER_ATTRIBUTE_ID_TO_CHECK
                #   value: "${AUTH_LDAP_REFERRAL_USER_ATTRIBUTE_ID_TO_CHECK}"
                # - name: AUTH_ROLE_MAPPER_ROLES_PROPERTIES
                #   value: "${AUTH_ROLE_MAPPER_ROLES_PROPERTIES}"
                # - name: AUTH_ROLE_MAPPER_REPLACE_ROLE
                #   value: "${AUTH_ROLE_MAPPER_REPLACE_ROLE}"
                
parameters:
  - name: NAMESPACE
    displayName: Openshift namespace (project)
    description: Openshift namespace (project) this application resides in
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name
  - name: BUILDER_IMAGE_NAME
    displayName: Name of the modified KIE server builder image
    required: true
  - name: KIE_MEMORY_LIMIT
    displayName: Maximum memory that an instance is allowed to use.
    required: false
    default: 2Gi
  - name: KIE_SERVER_MODE
    displayName: Kie server mode
    description: The KIE Server mode. Valid values are 'DEVELOPMENT' or 'PRODUCTION'. In production mode, you can not deploy SNAPSHOT versions of artifacts on the KIE server and can not change the version of an artifact in an existing container. (Sets the org.kie.server.mode system property).
    default: PRODUCTION
    required: false
  - name: KIE_CONTAINER
    displayName: Kie container to deploy
    required: true