---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${SERVICE}
    spec:
      replicas: 1
      selector:
        name: ${SERVICE}
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: ${SERVICE}
        spec:
          containers:
          - env:
            - name: NAMESPACE
              value: ${NAMESPACE}
            - name: MYSQL_HOST
              value: database.${NAMESPACE}.svc.cluster.local
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "yellowdog"
            - name: MYSQL_USER
              value: "yellowdog"
            - name: MYSQL_PASSWORD
              value: "YellowDog1234!@#$"
            imagePullPolicy: Always
            name: hr-authentication
            image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${SERVICE}:${IMAGE_VERSION}
          imagePullSecrets:
            - name: artifactory-puller            
      triggers:
      - type: ConfigChange
parameters:
  - name: NAMESPACE
    displayName: Openshift namespace (project)
    description: Openshift namespace (project) this application resides in
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
