---
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata: 
    labels:
      app: ${APP_NAME}
    name: kie-admin-user
  type: Opaque
  data:
    # Change these to something secure in base64 format
    # rhpamAdmin:p4ssw0rd1! 
    username: cmhwYW1BZG1pbgo=
    password: cDRzc3cwcmQxIQo=
parameters:
  - name: APP_NAME
    required: true
    description: The app name