---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      external: ${SERVICE}
      app:  ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: https
    selector:
      name: ${SERVICE}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      external: ${SERVICE}
      app:  ${APP_NAME}
    name: ${APP_NAME}-kieserver-ping
  spec:
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      name: jgroups
    selector:
      name: ${SERVICE}
    sessionAffinity: None
    type: ClusterIP
parameters:
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name