---
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${APP_NAME}-kieserver
    labels:
      app: ${APP_NAME}
parameters:
  - name: APP_NAME
    required: true
    description: The app name